10.2-6 SettingsInteractor
1vank1n/surf-places pull request #46
Opened 2021-04-17 08:55 UTC by 1vank1n

2021-04-21 17:12 UTC, artem-zaitsev requested changes
На UI пока ок, надо еще разобраться с построением слоев.
Слейте все и новой веткой отрефакторите сетевой слой.

Ну и следующую итерацию ДЗ уже одним ПРом с рефакторингом сделайте

2021-04-21 17:12 UTC, artem-zaitsev commented on lib/data/repository/place_respository.dart
> +    Dio dio = Dio(
Вообще конфигурацию клиента лучше передавать в конструктор извне. Если у вас будет два и больше репозиториев - в вашем случае будете дублировать и копипастить код.

В целом таким классом - поставщиком вполне мог быть класс Api. Только он тоде не должен иметь статичные методы.

Вы просто должны создавать сначала(псевдокод)
var api = Api(dio: Dio(...));

PlaceRepository(api: api);

Что-то в это духе.

2021-04-21 17:12 UTC, artem-zaitsev commented on lib/data/repository/place_respository.dart
> +    Dio dio = Dio(
Это позволит вам в случае тестов или например демо окружения создать Api. c другим Dio и передать другой дио в репозиторий. 
А самое интересное, что репозиторий вообще не будет знать о существовании Dio: он будет общаться только с интерфейсом Api. Это позволит заменить Dio на любую другуюю имплементацию без ущерба другим слоям.

2021-04-21 17:12 UTC, artem-zaitsev commented on lib/data/network/api.dart
> +class Api {
Этот класс должен избавится от статики и выполянть слежующую функцию: описовать интерфейс взаимодейтсвия с сервером(кстати под кажды репо такой АПИ может быть свой)

2021-04-21 17:12 UTC, artem-zaitsev commented on lib/data/network/api.dart
> +  static final _dio = Dio(
Конфигурацией Dio и его поставкой в Api( а здесь тоже на поставлять извне, писал выше почему) - должен заниматься отдельный класс/функция.(не статическая)

2021-04-22 07:00 UTC, 1vank1n commented on lib/data/network/api.dart
> +class Api {
Этот класс не используется. Это атовизм от прошлой реализации. Перенёс всю бизнес-логику в PlaceRepository

2021-04-22 07:01 UTC, 1vank1n commented on lib/data/network/api.dart
> +  static final _dio = Dio(
Повторюсь класс не используется. Файл удалял в прошлых ветках, а при мёрдже прошлых веток, файл остался ) сейчас его потру.

2021-04-22 10:35 UTC, merged